import {
  Badge,
  BadgePlus,
  Bolt,
  Boxes,
  Brain,
  ChartColumnBig,
  ChartPie,
  ChartSpline,
  CircleDot,
  CircleHelp,
  CirclePlus,
  Cog,
  Database,
  FileWarning,
  Grid2x2,
  Grid2x2Plus,
  LaptopMinimal,
  Package,
  PackagePlus,
  Percent,
  Tickets,
  UserPlus,
  Users,
  type LucideIcon,
} from "lucide-react";

export const data = {
  user: {
    name: "shadcn",
    email: "m@example.com",
    avatar: "/avatars/shadcn.jpg",
  },
  navMain: [
    { title: "overview", url: "", icon: ChartSpline },
    { title: "Dashboard", url: "dashboard", icon: ChartPie },
    { title: "Analytics", url: "analytics", icon: ChartColumnBig },
  ] as Array<{ title: string; url: string; icon: LucideIcon }>,

  navSecondary: [
    { title: "Support Help", url: "help", icon: CircleHelp },
    { title: "Settings", url: "settings", icon: Cog },
    { title: "Bot AI", icon: Brain, url: "prompts" },
    { title: "Appearance", icon: LaptopMinimal, url: "appearance" },
    { title: "Integrations", url: "integrations", icon: Bolt },
    { title: "Data Library", url: "data-library", icon: Database },
    { title: "Reports", url: "reports", icon: FileWarning },
  ] as Array<{ title: string; url: string; icon: LucideIcon }>,
  documents: [
    // { name: "Data Library", url: "data-library", icon: Database },
    { name: "categories", url: "categories", icon: Grid2x2 },
    { name: "add category", url: "add-category", icon: Grid2x2Plus },
    { name: "members", url: "members", icon: Users },
    { name: "add member", url: "add-member", icon: UserPlus },
    { name: "products", url: "products", icon: Package },
    { name: "add product", url: "add-product", icon: PackagePlus },
    { name: "Brands", url: "brands", icon: Badge },
    { name: "add brand", url: "add-brand", icon: BadgePlus },
    { name: "Subcategories", url: "subcategories", icon: CircleDot },
    { name: "add subcategory", url: "add-subcategory", icon: CirclePlus },
    { name: "Coupons", url: "coupons", icon: Percent },
    { name: "add coupon", url: "add-coupon", icon: Tickets },
    { name: "Orders", url: "orders", icon: Boxes },
  ] as Array<{ name: string; url: string; icon: LucideIcon }>,
};
